name: example-environment

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.6
  - sqlalchemy
  - pandas
  - pyodbc
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - pip=20.2.*
