# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui',
# licensing of 'mainWindow.ui' applies.
#
# Created: Fri Nov 20 14:06:30 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(416, 715)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 431, 701))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 60, 47, 13))
        self.label.setText("")
        self.label.setObjectName("label")
        self.formGroupBox = QtWidgets.QGroupBox(self.frame)
        self.formGroupBox.setGeometry(QtCore.QRect(10, 180, 391, 101))
        self.formGroupBox.setObjectName("formGroupBox")
        self.authLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.authLayout.setContentsMargins(10, 10, 10, 10)
        self.authLayout.setObjectName("authLayout")
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setObjectName("label_2")
        self.authLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.authTypeBox = QtWidgets.QComboBox(self.formGroupBox)
        self.authTypeBox.setObjectName("authTypeBox")
        self.authTypeBox.addItem("")
        self.authTypeBox.addItem("")
        self.authLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.authTypeBox)
        self.label_3 = QtWidgets.QLabel(self.formGroupBox)
        self.label_3.setObjectName("label_3")
        self.authLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.usernameEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.usernameEdit.setEnabled(True)
        self.usernameEdit.setObjectName("usernameEdit")
        self.authLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.usernameEdit)
        self.label_4 = QtWidgets.QLabel(self.formGroupBox)
        self.label_4.setObjectName("label_4")
        self.authLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pwdEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.pwdEdit.setEnabled(True)
        self.pwdEdit.setObjectName("pwdEdit")
        self.authLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pwdEdit)
        self.formGroupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.formGroupBox_2.setGeometry(QtCore.QRect(10, 60, 391, 101))
        self.formGroupBox_2.setObjectName("formGroupBox_2")
        self.databaseLayout = QtWidgets.QFormLayout(self.formGroupBox_2)
        self.databaseLayout.setContentsMargins(10, 10, 10, 10)
        self.databaseLayout.setObjectName("databaseLayout")
        self.label_5 = QtWidgets.QLabel(self.formGroupBox_2)
        self.label_5.setObjectName("label_5")
        self.databaseLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.instanceBox = QtWidgets.QComboBox(self.formGroupBox_2)
        self.instanceBox.setObjectName("instanceBox")
        self.databaseLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.instanceBox)
        self.label_7 = QtWidgets.QLabel(self.formGroupBox_2)
        self.label_7.setObjectName("label_7")
        self.databaseLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.destinationBox = QtWidgets.QComboBox(self.formGroupBox_2)
        self.destinationBox.setObjectName("destinationBox")
        self.destinationBox.addItem("")
        self.destinationBox.addItem("")
        self.databaseLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.destinationBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.destEdit = QtWidgets.QLineEdit(self.formGroupBox_2)
        self.destEdit.setEnabled(False)
        self.destEdit.setObjectName("destEdit")
        self.horizontalLayout_4.addWidget(self.destEdit)
        self.chooseButton = QtWidgets.QPushButton(self.formGroupBox_2)
        self.chooseButton.setObjectName("chooseButton")
        self.horizontalLayout_4.addWidget(self.chooseButton)
        self.databaseLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(100, 10, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.backupButton = QtWidgets.QPushButton(self.frame)
        self.backupButton.setGeometry(QtCore.QRect(320, 630, 81, 31))
        self.backupButton.setObjectName("backupButton")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 360, 391, 251))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.listLayout = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.listLayout.setContentsMargins(0, 0, 0, 0)
        self.listLayout.setObjectName("listLayout")
        self.databaseListWidget = QtWidgets.QListWidget(self.formLayoutWidget_3)
        self.databaseListWidget.setObjectName("databaseListWidget")
        self.listLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.databaseListWidget)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 280, 391, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connectionButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.connectionButton.setObjectName("connectionButton")
        self.horizontalLayout.addWidget(self.connectionButton)
        self.connectionLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.connectionLabel.setObjectName("connectionLabel")
        self.horizontalLayout.addWidget(self.connectionLabel)
        self.horizontalLayout.addWidget(self.connectionLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 416, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuLicense = QtWidgets.QMenu(self.menuBar)
        self.menuLicense.setObjectName("menuLicense")
        mainWindow.setMenuBar(self.menuBar)
        self.actionLicense = QtWidgets.QAction(mainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuLicense.addAction(self.actionLicense)
        self.menuLicense.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuLicense.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtWidgets.QApplication.translate("mainWindow", "MainWindow", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("mainWindow", "Authentication", None, -1))
        self.authTypeBox.setItemText(0, QtWidgets.QApplication.translate("mainWindow", "Windows Authentication", None, -1))
        self.authTypeBox.setItemText(1, QtWidgets.QApplication.translate("mainWindow", "SQL Authentication", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("mainWindow", "Username", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("mainWindow", "Password", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("mainWindow", "Server Name", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("mainWindow", "Backup Destination", None, -1))
        self.destinationBox.setItemText(0, QtWidgets.QApplication.translate("mainWindow", "Device", None, -1))
        self.destinationBox.setItemText(1, QtWidgets.QApplication.translate("mainWindow", "Google Drive", None, -1))
        self.chooseButton.setText(QtWidgets.QApplication.translate("mainWindow", "Choose", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("mainWindow", "SQL SERVER BACKUP TOOL", None, -1))
        self.backupButton.setText(QtWidgets.QApplication.translate("mainWindow", "Backup", None, -1))
        self.connectionButton.setText(QtWidgets.QApplication.translate("mainWindow", "Test Connection", None, -1))
        self.connectionLabel.setText(QtWidgets.QApplication.translate("mainWindow", "TextLabel", None, -1))
        self.okButton.setText(QtWidgets.QApplication.translate("mainWindow", "Ok", None, -1))
        self.menuLicense.setTitle(QtWidgets.QApplication.translate("mainWindow", "License", None, -1))
        self.actionLicense.setText(QtWidgets.QApplication.translate("mainWindow", "License", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("mainWindow", "About", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

